<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115204820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE poll (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84BCFA454B89032C ON poll (post_id)');
        $this->addSql('CREATE TABLE poll_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, poll_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B68343EB3C947C0F ON poll_option (poll_id)');
        $this->addSql('CREATE TABLE poll_option_user (poll_option_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (poll_option_id, user_id))');
        $this->addSql('CREATE INDEX IDX_57FF0BA86C13349B ON poll_option_user (poll_option_id)');
        $this->addSql('CREATE INDEX IDX_57FF0BA8A76ED395 ON poll_option_user (user_id)');
        $this->addSql('ALTER TABLE poll ADD CONSTRAINT FK_84BCFA454B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE poll_option ADD CONSTRAINT FK_B68343EB3C947C0F FOREIGN KEY (poll_id) REFERENCES poll (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE poll_option_user ADD CONSTRAINT FK_57FF0BA86C13349B FOREIGN KEY (poll_option_id) REFERENCES poll_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE poll_option_user ADD CONSTRAINT FK_57FF0BA8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE poll DROP CONSTRAINT FK_84BCFA454B89032C');
        $this->addSql('ALTER TABLE poll_option DROP CONSTRAINT FK_B68343EB3C947C0F');
        $this->addSql('ALTER TABLE poll_option_user DROP CONSTRAINT FK_57FF0BA86C13349B');
        $this->addSql('ALTER TABLE poll_option_user DROP CONSTRAINT FK_57FF0BA8A76ED395');
        $this->addSql('DROP TABLE poll');
        $this->addSql('DROP TABLE poll_option');
        $this->addSql('DROP TABLE poll_option_user');
    }
}
